server:
  port: 7070

logging:
  level:
    org.springframework: DEBUG

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  messages:
    basename: messages

  security:
    user:
      name: user
      password: password

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect